#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse

from defaults import defaults
from bot import Lunchbot
from utils import parse_date_overrides


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument('command', choices=['prelunch', 'lunch', 'asf'])
    parser.add_argument('--production', action='store_true', help='actually send Zulip messages')
    parser.add_argument('--zulip-username', default=defaults['zulip_username'])
    parser.add_argument('--zulip-api-key', default=defaults['zulip_api_key'])
    parser.add_argument('--zulip-site', default=defaults['zulip_site'])
    parser.add_argument('--zulip-stream', default=defaults['zulip_stream'])
    parser.add_argument('--date-override', action='append', default=defaults['date_overrides'].split(','), metavar='(+|-)yyyy-mm-dd', help='override running on a date')

    args = vars(parser.parse_args())
    args['date_overrides'] = parse_date_overrides(args['date_override'])

    return args


if __name__ == '__main__':
    options = parse_args()

    lunchbot = Lunchbot(
        options['zulip_username'],
        options['zulip_api_key'],
        options['zulip_site'],
        options['zulip_stream'],
        date_overrides=options['date_overrides'],
        test_mode=(not options['production'])
    )

    lunchbot.handle_command(options['command'])
